spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1011268384713-bf9q63sqf1o3d3j60j7abcvn912udtrq.apps.googleusercontent.com
            clientSecret: lOV6Xrg-rpeg3Ber9MVNKegp
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  datasource:
    url: jdbc:h2:mem:test;INIT=create schema IF NOT EXISTS mydb;DB_CLOSE_DELAY=-1

app:
  tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
  tokenExpirationMsec: 864000000
  authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect
    - myandroidapp://oauth2/redirect
    - myiosapp://oauth2/redirect
